### ISSUE TITLE
TypeScript should not be a dependency?

### ISSUE THREAD

**Issue by lydell** [apiel/run-screen#1]
Hi, and thanks for making this tool! This is exactly what I’ve been looking for some time 😍 

A quick question – TypeScript is listed in `"dependencies"` in package.json, but it should be in `"devDependencies"`, right? Moving it there would save around 50 MB in install size :)

**Comment by apiel** [comment]
You are right ;-) I don't know why, I do this in all my project, only for typescript. Thx for the issue

**Comment by apiel** [comment]
done

**Comment by lydell** [comment]
Awesome, thanks for the speedy fix!
